name: Integration Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t dotnet-nim-test -f tests/Dockerfile .

    - name: Run Tests (Server: .NET, Client: Nim)
      run: |
        docker run --rm dotnet-nim-test powershell -Command "
          Start-Process -NoNewWindow -FilePath 'C:/app/tests/dotnet/Server/bin/Release/Server.exe'
          Start-Sleep -Seconds 5
          & 'C:/app/tests/nim/client.exe'
          if ($LASTEXITCODE -ne 0) { exit 1 }
          Stop-Process -Name 'Server' -Force
        "

    - name: Run Reverse Tests (Server: Nim, Client: .NET)
      run: |
        docker run --rm dotnet-nim-test powershell -Command "
          Start-Process -NoNewWindow -FilePath 'C:/app/tests/nim/server.exe'
          Start-Sleep -Seconds 5
          & 'C:/app/tests/dotnet/Client/bin/Release/Client.exe' 'tcp://localhost:8081/EchoService'
          if ($LASTEXITCODE -ne 0) { exit 1 }
          Stop-Process -Name 'server' -Force
        "
