name: Nim Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        nim-version: ['2.0.14', '2.2.0']
      fail-fast: false  # Continue with other OS/version combinations even if one fails
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Nim environment
      uses: jiro4989/setup-nim-action@v2.2.2
      with:
        nim-version: ${{ matrix.nim-version }}
        
    - name: Install dependencies
      run: |
        nimble refresh
        nimble install -y
        nimble refresh
        
    - name: Run tests
      run: nimble test
        
    # Caching strategy adapted for each OS
    - name: Cache nimble packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.nimble
          ${{ github.workspace }}/nimcache
          ${{ env.APPDATA }}/nimble  # Windows-specific
          ~/Library/Nimble           # macOS-specific
        key: ${{ runner.os }}-nim-${{ matrix.nim-version }}-v1
        restore-keys: |
          ${{ runner.os }}-nim-${{ matrix.nim-version }}-
          ${{ runner.os }}-nim-
